# -*- coding: utf-8 -*-
"""Sleep_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJjHg6Zc-n-Md8ml-4u7o8NYb9AVq3da
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

"""# Carga de CSV y categorizacion de datos"""

datset = pd.read_csv('SSD_V10 (10).csv')

datset.rename(columns = {'Wakeup time':'Wakeup_time', 'Sleep duration':'Sleep_duration',"Sleep efficiency":"Sleep_efficiency",
                     "REM sleep percentage":"REM_sleep_percentage","Deep sleep percentage":"Deep_sleep_percentage",
                     "Light sleep percentage":"Light_sleep_percentage","Caffeine consumption":"Caffeine_consumption",
                     "Alcohol consumption":"Alcohol_consumption","Smoking status":"Smoking_status","Exercise frequency":"Exercise_frequency"}, inplace = True)

datset.head(5)

datset.head(5)

le = LabelEncoder()

norm_datset = datset.drop(['Bedtime', 'Wakeup_time', 'ID','Calidad_sueño'], axis=1)

norm_datset['Gender'] = le.fit_transform(norm_datset['Gender'])
norm_datset['Smoking_status'] = le.fit_transform(norm_datset['Smoking_status'])

norm_datset.dtypes

norm_datset['Gender'] = norm_datset['Gender'].astype('category')
norm_datset['Smoking_status'] = norm_datset['Smoking_status'].astype('category')

"""# Entrenamiento del modelo con 453 datos"""

norm_datset.corr()

X = norm_datset.drop(['Sleep_efficiency'], axis=1) #variables independientes
y = norm_datset['Sleep_efficiency'] #variable dependiente

#Division de los datos en 30% prueba y 70% entrenamiento


#hiperparametros aleatorios para calcular los valores optimos del modelo
"""
n_estimators = [100, 200, 300]
max_depth = [10, 20, 30]
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2, 4]

parameters = {
    'n_estimators': n_estimators,
    'max_depth': max_depth,
    'min_samples_split': min_samples_split,
    'min_samples_leaf': min_samples_leaf
}

rfr_cv = GridSearchCV(rfr, parameters, cv=5, n_jobs=-1)
rfr_cv.fit(X_train, y_train)

best_estimators = rfr_cv.best_params_['n_estimators']
best_max_depth = rfr_cv.best_params_['max_depth']
best_min_samples_split = rfr_cv.best_params_['min_samples_split']
best_min_samples_leaf = rfr_cv.best_params_['min_samples_leaf']


print(f"Mejor cantidad de arboles: {best_estimators}")
print(f"Mejor profundidad máxima: {best_max_depth}")
print(f"Mejor mínimo de muestras para dividir: {best_min_samples_split}")
print(f"Mejor mínimo de muestras en una hoja: {best_min_samples_leaf}")
"""
#Usar los mejores parametros para hacer el modelo mas preciso y comapararlo

def cargar_modelo():
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)

    rfr = RandomForestRegressor(random_state=1234)
    # Aquí puedes definir tu modelo entrenado
    model = RandomForestRegressor(n_estimators=300,max_depth=20,min_samples_split=5,min_samples_leaf=2)
    # Predecir en el conjunto de prueba
    model.fit(X_train, y_train)
    Y_pred = model.predict(X_test)
    return model

# Función para hacer predicciones
def predecir(model, input_data):
    input_array = np.array(input_data).reshape(1, -1)
    prediction = model.predict(input_array)
    return prediction[0]

"""
cv_results = rfr_cv.cv_results_

df_results = pd.DataFrame({
    'n_estimators': cv_results['param_n_estimators'].data,
    'max_depth': cv_results['param_max_depth'].data,
    'min_samples_split': cv_results['param_min_samples_split'].data,
    'min_samples_leaf': cv_results['param_min_samples_leaf'].data,
    'r2_score': cv_results['mean_test_score'],  # R² es la métrica predeterminada en GridSearchCV
})

# Evaluar el modelo en el conjunto de validación para obtener MSE y MAE
y_pred = rfr_cv.best_estimator_.predict(X_test)  # Predicciones con los mejores hiperparámetros

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

# Agregar MSE y MAE al DataFrame
df_results['mse'] = mse
df_results['mae'] = mae

# Mostrar los resultados
print(df_results)
"""
"""# Grafico de R2"""
"""
plt.figure(figsize=(8, 5))
sns.lineplot(x='n_estimators', y='r2_score', data=df_results, marker='o', hue='max_depth')
plt.xlabel("Número de árboles (n_estimators)")
plt.ylabel("R² Score")
plt.title("Efecto de n_estimators en R²")
plt.legend(title="Profundidad Máxima")
plt.show()

# Obtener las predicciones del modelo con los mejores hiperparámetros
y_pred = rfr_cv.best_estimator_.predict(X_test)

# Crear la figura
plt.figure(figsize=(8, 6))

# Índices de los datos para graficar en el eje X (solo para mejor visualización)
indices = np.arange(len(y_test))

# Graficar los valores reales (en azul)
plt.scatter(indices, y_test, color='blue', alpha=0.6, label="Valores Reales")

# Graficar los valores predichos (en rojo)
plt.scatter(indices, y_pred, color='red', alpha=0.6, label="Valores Predichos")

# Etiquetas y título
plt.xlabel("Índice de Muestra")
plt.ylabel("Valor")
plt.title("Comparación de Valores Reales y Predichos")
plt.legend()
plt.grid(True)

# Mostrar el gráfico
plt.show()
"""
"""# Código para la generación del CSV sin usar el modelo"""
"""
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Definir el número de muestras a generar
num_samples = 1600

# Generar edades dentro del rango [16, 69] con distribución lógica
ages = np.random.choice(range(16, 70), num_samples, p=np.ones(54) / 54)

# Generar género de manera aleatoria
genders = np.random.choice(["Male", "Female"], num_samples)

# Generar estado de fumador (0 = No, 1 = Sí), menores de 16 no fuman
smoking_status = np.where(ages < 16, 0, np.random.choice([0, 1], num_samples, p=[0.8, 0.2]))

# Generar consumo de cafeína (en tazas)
caffeine_consumption = np.random.choice([0, 1, 2, 3, 4], num_samples, p=[0.2, 0.3, 0.25, 0.15, 0.1])

# Generar consumo de alcohol (0 a 5), menores de 16 no consumen
alcohol_consumption = np.where(ages < 16, 0, np.random.choice(range(6), num_samples, p=[0.3, 0.3, 0.2, 0.1, 0.07, 0.03]))

# Generar frecuencia de ejercicio (0 a 5)
exercise_frequency = np.random.choice(range(6), num_samples)

# Generar horas de dormir y despertar
bedtimes = []
wake_times = []
sleep_durations = []

for i in range(num_samples):
    # Definir fecha aleatoria en 2024 con mes y día variables
    month = np.random.randint(1, 13)
    day = np.random.randint(1, 29)
    base_date = datetime(2024, month, day)

    # Definir duración base del sueño
    base_sleep = np.random.uniform(4.5, 9)

    if ages[i] <= 18:
        base_sleep = np.random.uniform(7, 10)
        bedtime_hour = np.random.randint(20, 22)
    elif ages[i] <= 30:
        base_sleep = np.random.uniform(4, 9)
        interval_1 = np.arange(20, 24)  # De 22 a 23
        interval_2 = np.arange(0, 4)    # De 0 a 3
        # Une los intervalos
        combined_intervals = np.concatenate((interval_1, interval_2))
        # Elige una hora aleatoria de los intervalos combinados
        bedtime_hour = np.random.choice(combined_intervals)
    elif ages[i] <= 50:
        base_sleep = np.random.uniform(5.5, 8)
        bedtime_hour = np.random.randint(21, 23)
    else:
        base_sleep = np.random.uniform(5, 7.5)
        bedtime_hour = np.random.randint(20, 22)

    # Ajustar por cafeína y alcohol
    if caffeine_consumption[i] >= 4:
        base_sleep -= np.random.uniform(0.5, 1.5)
    if alcohol_consumption[i] >= 3:
        base_sleep -= np.random.uniform(0.3, 1)
    if smoking_status[i] == 1:
        base_sleep -= np.random.uniform(0.5, 1.5)

    # Asegurar duración en rango lógico
    sleep_duration = max(3.5, min(10, base_sleep))
    sleep_durations.append(round(sleep_duration, 1))

    # Definir hora de dormir y despertar
    bedtime = base_date + timedelta(hours=int(bedtime_hour), minutes=np.random.randint(0, 60))
    wakeup_time = bedtime + timedelta(hours=int(sleep_duration), minutes=int((sleep_duration % 1) * 60))

    bedtimes.append(bedtime.strftime("%Y-%m-%d %H:%M:%S"))
    wake_times.append(wakeup_time.strftime("%Y-%m-%d %H:%M:%S"))

# Generar porcentaje de sueño REM, profundo y ligero
rem_sleep_percentage = np.round(np.random.uniform(20, 25, num_samples), 2)
deep_sleep_percentage = np.round(np.random.uniform(15, 30, num_samples), 2)
light_sleep_percentage = np.round(100 - (rem_sleep_percentage + deep_sleep_percentage), 2)

# Ajustar por cafeína y fumar
for i in range(num_samples):
    if caffeine_consumption[i] >= 4 or smoking_status[i] == 1:
        deep_sleep_percentage[i] -= np.random.uniform(2, 5)
        rem_sleep_percentage[i] -= np.random.uniform(1, 3)
        light_sleep_percentage[i] = np.round(100 - (rem_sleep_percentage[i] + deep_sleep_percentage[i]), 2)

# Generar número de despertares
awakenings = np.random.randint(0, 3, num_samples)
for i in range(num_samples):
    if caffeine_consumption[i] >= 4 or smoking_status[i] == 1:
        awakenings[i] += np.random.randint(1, 3)
    if alcohol_consumption[i] >= 3:
        awakenings[i] += np.random.randint(1, 2)

# Generar eficiencia del sueño
sleep_efficiency = 85 + (np.array(sleep_durations) - 7) * 2
sleep_efficiency -= awakenings * 2
sleep_efficiency -= caffeine_consumption * 1.5
sleep_efficiency -= smoking_status * 3
sleep_efficiency = np.clip(sleep_efficiency, 50, 100)

# Crear DataFrame con el orden solicitado
data = pd.DataFrame({
    "Age": ages,
    "Gender": genders,
    "Bedtime": bedtimes,
    "Wakeup time": wake_times,
    "Sleep duration": sleep_durations,
    "Sleep efficiency": sleep_efficiency,
    "REM sleep_percentage": rem_sleep_percentage,
    "Deep_sleep percentage": deep_sleep_percentage,
    "Light sleep percentage": light_sleep_percentage,
    "Awakenings": awakenings,
    "Caffeine consumption": caffeine_consumption,
    "Alcohol consumption": alcohol_consumption,
    "Smoking status": smoking_status,
    "Exercise frequency": exercise_frequency
})

# Guardar en CSV
file_path = "SSD_V5.csv"
data.to_csv(file_path, index=False,float_format='%.2f') #En caso, de querer visualizarlo bonito en el excel agregar: sep=';', encoding='utf-8'
# Mostrar las primeras filas del dataset generado
data.head(), file_path
"""
"""# Graficas de los datos"""
"""
dataset = pd.read_csv('SSD_V5.csv')#cargamos el nuevo dataset
dataset.rename(columns = {'Wakeup time':'Wakeup_time', 'Sleep duration':'Sleep_duration',"Sleep efficiency":"Sleep_efficiency",
                     "REM sleep percentage":"REM_sleep_percentage","Deep sleep percentage":"Deep_sleep_percentage",
                     "Light sleep percentage":"Light_sleep_percentage","Caffeine consumption":"Caffeine_consumption",
                     "Alcohol consumption":"Alcohol_consumption","Smoking status":"Smoking_status","Exercise frequency":"Exercise_frequency"}, inplace = True)
dataset.head(5)

le = LabelEncoder()

norm_dataset = dataset.drop(['Bedtime', 'Wakeup_time'], axis=1)

norm_dataset['Gender'] = le.fit_transform(norm_dataset['Gender'])
norm_dataset['Smoking_status'] = le.fit_transform(norm_dataset['Smoking_status'])
norm_dataset.dtypes

norm_dataset['Gender'] = norm_datset['Gender'].astype('category')
norm_dataset['Smoking_status'] = norm_datset['Smoking_status'].astype('category')
norm_dataset.dtypes

norm_dataset.head(5)

sns.pairplot(norm_dataset)

# Columnas continuas
columnas_continuas = [
    'Age', 'Sleep_duration', 'Sleep_efficiency',
    'REM sleep_percentage', 'Deep_sleep percentage',
    'Light_sleep_percentage', 'Awakenings',
    'Caffeine_consumption', 'Alcohol_consumption',
    'Exercise_frequency'
]

for columna in columnas_continuas:
    plt.figure(figsize=(10, 6))
    sns.boxplot(norm_dataset[columna])
    plt.title(f'Histograma de {columna}')
    plt.xlabel(columna)
    plt.ylabel('Frecuencia')
    plt.show()

for columna in columnas_continuas:
    plt.figure(figsize=(10, 6))
    sns.histplot(norm_dataset[columna], kde=True)
    plt.title(f'Histograma de {columna}')
    plt.xlabel(columna)
    plt.ylabel('Frecuencia')
    plt.show()

plt.figure(figsize=(8,5))
sns.histplot(norm_dataset["Caffeine_consumption"], bins=20, kde=True, color="steelblue")
plt.title("Distribución del Consumo de Cafeína")
plt.xlabel("Caffeine_consumption")
plt.ylabel("Frecuencia")
plt.show()

# Detectar outliers con el rango intercuartílico (IQR)
Q1 = norm_dataset["Caffeine_consumption"].quantile(0.25)
Q3 = norm_dataset["Caffeine_consumption"].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = norm_dataset[(norm_dataset["Caffeine_consumption"] < lower_bound) | (norm_dataset["Caffeine_consumption"] > upper_bound)]
print(f"Cantidad de outliers detectados: {len(outliers)}")

# Visualizar outliers en un boxplot
plt.figure(figsize=(8,5))
sns.boxplot(x=norm_dataset["Caffeine_consumption"], color="lightcoral")
plt.title("Boxplot del Consumo de Cafeína")
plt.xlabel("Caffeine_consumption")
plt.show()

norm_dataset.corr()
"""
"""# Entrenando modelo con el CSV generado"""
"""
norm_dataset.corr()

X2 = norm_dataset.drop(['Sleep_efficiency'], axis=1) #variables independientes
y2 = norm_dataset['Sleep_efficiency'] #variable dependiente

#Division de los datos en 30% prueba y 70% entrenamiento
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.3, random_state=1234)

rfr = RandomForestRegressor(random_state=1234)

#hiperparametros aleatorios para calcular los valores optimos del modelo
n_estimators = [100, 200, 300]
max_depth = [10, 20, 30]
min_samples_split = [2, 5, 10]
min_samples_leaf = [1, 2, 4]

parameters = {
    'n_estimators': n_estimators,
    'max_depth': max_depth,
    'min_samples_split': min_samples_split,
    'min_samples_leaf': min_samples_leaf
}

rfr_cv = GridSearchCV(rfr, parameters, cv=5, n_jobs=-1)
rfr_cv.fit(X_train2, y_train2)

best_estimators = rfr_cv.best_params_['n_estimators']
best_max_depth = rfr_cv.best_params_['max_depth']
best_min_samples_split = rfr_cv.best_params_['min_samples_split']
best_min_samples_leaf = rfr_cv.best_params_['min_samples_leaf']


print(f"Mejor cantidad de arboles: {best_estimators}")
print(f"Mejor profundidad máxima: {best_max_depth}")
print(f"Mejor mínimo de muestras para dividir: {best_min_samples_split}")
print(f"Mejor mínimo de muestras en una hoja: {best_min_samples_leaf}")

#Usar los mejores parametros para hacer el modelo mas preciso y comapararlo
model2 = RandomForestRegressor(n_estimators=300,
                             max_depth=20,
                             min_samples_split=2,
                             min_samples_leaf=2)

# Predecir en el conjunto de prueba
model2.fit(X_train2, y_train2)
Y_pred2 = model2.predict(X_test2)
y_train_pred2 = model2.predict(X_train2)
r2_train = r2_score(y_train2, y_train_pred2)

print(f'R² en entrenamiento: {r2_train:.4f}')

# Calcular métricas
mse = mean_squared_error(y_test2, Y_pred2)
mae = mean_absolute_error(y_test2, Y_pred2)
r2 = r2_score(y_test2, Y_pred2)

print(f"Error Cuadrático Medio (MSE): {str(np.round(mse, 3))}")
print(f"Error Absoluto Medio (MAE): {str(np.round(mae, 3))}")
print(f"Coeficiente de Determinación (R²): {str(np.round(r2, 4))}")

cv_results2 = rfr_cv.cv_results_

df_results2 = pd.DataFrame({
    'n_estimators': cv_results['param_n_estimators'].data,
    'max_depth': cv_results['param_max_depth'].data,
    'min_samples_split': cv_results['param_min_samples_split'].data,
    'min_samples_leaf': cv_results['param_min_samples_leaf'].data,
    'r2_score': cv_results['mean_test_score'],  # R² es la métrica predeterminada en GridSearchCV
})

# Evaluar el modelo en el conjunto de validación para obtener MSE y MAE
y_pred2 = rfr_cv.best_estimator_.predict(X_test2)  # Predicciones con los mejores hiperparámetros

mse = mean_squared_error(y_test2, y_pred2)
mae = mean_absolute_error(y_test2, y_pred2)

# Agregar MSE y MAE al DataFrame
df_results2['mse'] = mse
df_results2['mae'] = mae

# Mostrar los resultados
print(df_results2)
"""
"""# Graficas para R2"""
"""
plt.figure(figsize=(8, 5))
sns.lineplot(x='n_estimators', y='r2_score', data=df_results2, marker='o', hue='max_depth')
plt.xlabel("Número de árboles (n_estimators)")
plt.ylabel("R² Score")
plt.title("Efecto de n_estimators en R²")
plt.legend(title="Profundidad Máxima")
plt.show()

# Obtener las predicciones del modelo con los mejores hiperparámetros
y_pred2 = rfr_cv.best_estimator_.predict(X_test2)

# Crear la figura
plt.figure(figsize=(8, 6))

# Índices de los datos para graficar en el eje X (solo para mejor visualización)
indices = np.arange(len(y_test2))

# Graficar los valores reales (en azul)
plt.scatter(indices, y_test2, color='blue', alpha=0.6, label="Valores Reales")

# Graficar los valores predichos (en rojo)
plt.scatter(indices, y_pred2, color='red', alpha=0.6, label="Valores Predichos")

# Etiquetas y título
plt.xlabel("Índice de Muestra")
plt.ylabel("Valor")
plt.title("Comparación de Valores Reales y Predichos")
plt.legend()
plt.grid(True)

# Mostrar el gráfico
plt.show()
"""
"""# Código para la generación del CSV con el modelo para sleep_effiency"""
"""
import pandas as pd
import numpy as np
import joblib  # Para cargar el modelo entrenado
from datetime import datetime, timedelta

# Definir el número de muestras a generar
num_samples = 1600

# Generar edades dentro del rango [16, 69] con distribución lógica
ages = np.random.choice(range(16, 70), num_samples, p=np.ones(54) / 54)

# Generar género de manera aleatoria (0 = Male, 1 = Female)
genders = np.random.choice([0, 1], num_samples)

# Generar estado de fumador (0 = No, 1 = Sí), menores de 16 no fuman
smoking_status = np.where(ages < 16, 0, np.random.choice([0, 1], num_samples, p=[0.8, 0.2]))

# Generar consumo de cafeína (en tazas)
caffeine_consumption = np.random.choice([0, 1, 2, 3, 4], num_samples, p=[0.2, 0.3, 0.25, 0.15, 0.1])

# Generar consumo de alcohol (0 a 5), menores de 16 no consumen
alcohol_consumption = np.where(ages < 16, 0, np.random.choice(range(6), num_samples, p=[0.3, 0.3, 0.2, 0.1, 0.07, 0.03]))

# Generar frecuencia de ejercicio (0 a 5)
exercise_frequency = np.random.choice(range(6), num_samples)

# Generar horas de dormir y despertar
bedtimes = []
wake_times = []
sleep_durations = []

for i in range(num_samples):
    base_date = datetime(2024, np.random.randint(1, 13), np.random.randint(1, 29))
    base_sleep = np.random.uniform(4.5, 9)

    if ages[i] <= 18:
        base_sleep = np.random.uniform(7, 10)
        bedtime_hour = np.random.randint(20, 22)
    elif ages[i] <= 30:
        base_sleep = np.random.uniform(4, 9)
        bedtime_hour = np.random.choice(np.concatenate((np.arange(20, 24), np.arange(0, 4))))
    elif ages[i] <= 50:
        base_sleep = np.random.uniform(5.5, 8)
        bedtime_hour = np.random.randint(21, 23)
    else:
        base_sleep = np.random.uniform(5, 7.5)
        bedtime_hour = np.random.randint(20, 22)

    sleep_duration = max(3.5, min(10, base_sleep))
    sleep_durations.append(round(sleep_duration, 1))

    bedtime = base_date + timedelta(hours=int(bedtime_hour), minutes=np.random.randint(0, 60))
    wakeup_time = bedtime + timedelta(hours=int(sleep_duration), minutes=int((sleep_duration % 1) * 60))

    bedtimes.append(bedtime.strftime("%Y-%m-%d %H:%M:%S"))
    wake_times.append(wakeup_time.strftime("%Y-%m-%d %H:%M:%S"))

# Generar porcentaje de sueño REM, profundo y ligero
rem_sleep_percentage = np.round(np.random.uniform(20, 25, num_samples), 2)
deep_sleep_percentage = np.round(np.random.uniform(15, 30, num_samples), 2)
light_sleep_percentage = np.round(100 - (rem_sleep_percentage + deep_sleep_percentage), 2)

# Generar número de despertares
awakenings = np.random.randint(0, 3, num_samples)

# Crear DataFrame con los datos generados
data = pd.DataFrame({
    "Age": ages,
    "Gender": genders,
    "Bedtime": bedtimes,
    "Wakeup_time": wake_times,
    "Sleep_duration": sleep_durations,
    "Sleep_efficiency": sleep_efficiency,
    "REM_sleep_percentage": rem_sleep_percentage,
    "Deep_sleep_percentage": deep_sleep_percentage,
    "Light_sleep_percentage": light_sleep_percentage,
    "Awakenings": awakenings,
    "Caffeine_consumption": caffeine_consumption,
    "Alcohol_consumption": alcohol_consumption,
    "Smoking_status": smoking_status,
    "Exercise_frequency": exercise_frequency
})
# Seleccionar solo las columnas que el modelo espera
features = ["Age", "Gender", "Sleep_duration", "REM_sleep_percentage",
            "Deep_sleep_percentage", "Light_sleep_percentage",
            "Awakenings", "Caffeine_consumption", "Alcohol_consumption",
            "Smoking_status", "Exercise_frequency"]

# Predecir la eficiencia del sueño con el modelo entrenado
sleep_efficiency = model.predict(data[features])
data["Sleep_efficiency"] = sleep_efficiency

# Guardar en CSV
file_path = "SSD_V6_with_model.csv"
file_path2 = "SSD_V6.csv"
data.to_csv(file_path, index=False, sep=';', encoding='utf-8', float_format='%.2f')
data.to_csv(file_path2, index=False, float_format='%.2f')
# Mostrar las primeras filas del dataset generado
data.head(), file_path
"""
"""# Graficas de los datos"""
"""
dataset = pd.read_csv('SSD_V6.csv')#cargamos el nuevo dataset
dataset.head(5)

dataset.dtypes

le = LabelEncoder()

norm_dataset = datset.drop(['Bedtime', 'Wakeup_time'], axis=1)

norm_dataset['Gender'] = le.fit_transform(norm_dataset['Gender'])
norm_dataset['Smoking_status'] = le.fit_transform(norm_dataset['Smoking_status'])

norm_dataset.dtypes

norm_dataset['Gender'] = norm_datset['Gender'].astype('category')
norm_dataset['Smoking_status'] = norm_datset['Smoking_status'].astype('category')
norm_dataset.dtypes

norm_dataset.dtypes

sns.pairplot(norm_dataset)

# Columnas continuas
columnas_continuas = [
    'Age', 'Sleep_duration', 'Sleep_efficiency',
    'REM_sleep_percentage', 'Deep_sleep_percentage',
    'Light_sleep_percentage', 'Awakenings',
    'Caffeine_consumption', 'Alcohol_consumption',
    'Exercise_frequency'
]

for columna in columnas_continuas:
    plt.figure(figsize=(10, 6))
    sns.boxplot(norm_dataset[columna])
    plt.title(f'Histograma de {columna}')
    plt.xlabel(columna)
    plt.ylabel('Frecuencia')
    plt.show()

# Importar librerías necesarias
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


# Convertir columnas de fechas a formato datetime
dataset['Bedtime'] = pd.to_datetime(dataset['Bedtime'], errors='coerce')
dataset['Wakeup_time'] = pd.to_datetime(dataset['Wakeup_time'], errors='coerce')

# Eliminar columnas no numéricas
numeric_dataset = dataset.select_dtypes(include=[float, int])

# Calcular la matriz de correlación
corr_matrix = numeric_dataset.corr()

# Visualizar la matriz de correlación usando un mapa de calor
plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Matriz de Correlación')
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


# Convertir columnas de fechas a formato datetime si es necesario
dataset['Bedtime'] = pd.to_datetime(dataset['Bedtime'], errors='coerce')
dataset['Wakeup_time'] = pd.to_datetime(dataset['Wakeup_time'], errors='coerce')

# Seleccionar solo las columnas numéricas
numeric_dataset = dataset.select_dtypes(include=[float, int])

# Calcular las correlaciones específicas con 'Sleep_efficiency'
correlation_sleep_efficiency = numeric_dataset.corr()['Sleep_efficiency'].sort_values()

# Visualizar las correlaciones con un gráfico de barras
plt.figure(figsize=(10, 8))
sns.barplot(x=correlation_sleep_efficiency.values, y=correlation_sleep_efficiency.index, palette='coolwarm')
plt.title('Correlaciones con Sleep Efficiency')
plt.xlabel('Coeficiente de Correlación')
plt.ylabel('Características')
plt.show()
"""
"""# Graficas de R2"""
"""
import pandas as pd

# Convertir columnas de fechas a formato datetime si es necesario
dataset['Bedtime'] = pd.to_datetime(dataset['Bedtime'], errors='coerce')
dataset['Wakeup_time'] = pd.to_datetime(dataset['Wakeup_time'], errors='coerce')

# Seleccionar solo las columnas numéricas
numeric_dataset = dataset.select_dtypes(include=[float, int])

# Calcular las correlaciones específicas con 'Sleep_efficiency'
correlation_sleep_efficiency = numeric_dataset.corr()["Sleep_efficiency"].sort_values(ascending=False)

# Imprimir las correlaciones ordenadas
print(correlation_sleep_efficiency)
"""