### 1. Iniciar sesión (obtener token JWT)
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "1234"
}
### 2. Acceder a la Ruta Protegida de Admin (Usar Token)
GET http://127.0.0.1:8000/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NDE2NjA5OTB9.nB8HxRhuLVHUWXBuGcE0tEn1n0rMgBUEDL2hkTJ3lIQ

### 3. Logout (Invalidar Token)
POST http://127.0.0.1:8000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NDE2NjA5OTB9.nB8HxRhuLVHUWXBuGcE0tEn1n0rMgBUEDL2hkTJ3lIQ

### 4. Intentar Acceder a la Ruta Protegida Después del Logout
GET http://127.0.0.1:8000/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NDE2NjA5OTB9.nB8HxRhuLVHUWXBuGcE0tEn1n0rMgBUEDL2hkTJ3lIQ
### registrar usuario
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "name": "Test User",
  "password": "1234",
  "age": 25,
  "gender": true
}

### Test para el endpoint /ping
GET http://127.0.0.1:8000/ping
Content-Type: application/json
