### 2. Iniciar sesión (obtener token JWT)
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "1234"
}
### Get current user (protected)
GET http://localhost:8000/users/me
Authorization: Bearer <token>

### registrar usuario
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "name": "Test User",
  "password": "1234",
  "age": 25,
  "gender": true
}

### Test para el endpoint /ping
GET http://127.0.0.1:8000/ping
Content-Type: application/json
